### ISSUE TITLE
AFK -> leaveFeed - Errata in comment

### ISSUE THREAD

**Issue by MatiasMFM2001** [DaviiD1337/yagpdb_custom_commands#3]
Hi! In [line 4](https://github.com/DaviiD1337/yagpdb_custom_commands/blob/548243fa548fc5cf9cefd9994df9f5abdd8365dc/afk/leaveFeed.yagpdbcc#L4), `Leave Message3` should be `Leave Message`

That's all the issue xd ~~I'm lazy to clone and PR~~

**Comment by DaviiD1337** [comment]
Done.

Thanks.
